ghq get -p ahomu/Talkie
ghq get -p blockgiven/ruboty-gen
ghq get -p capistrano/capistrano
ghq get -p caskroom/homebrew-cask
ghq get -p h2o/h2o
ghq get -p harukasan/butter
ghq get -p heroku/node-js-sample
ghq get -p heroku/ruby-rails-sample
ghq get -p hitode909/rokuga
ghq get -p hshimoyama/xp_pair_programming
ghq get -p ikegawa-koshi/idol-handshake
ghq get -p kirikiriyamama/soror
ghq get -p kosenconf-2015-tokyo/kosenconf
ghq get -p mruby/mruby
ghq get -p nikuzuki/QuizMaker
ghq get -p nikuzuki/Taskapp
ghq get -p nikuzuki/UnaEscape
ghq get -p nikuzuki/demo_app3
ghq get -p r7kamura/retro-twitter-client
ghq get -p rails/rails
ghq get -p rcmdnk/homebrew-file
ghq get -p shinespark/electronic-facebook
ghq get -p spice-life/deeplearning
ghq get -p spice-life/kanoko
ghq get -p spice-life/kanoko-app
ghq get -p spice-life/miam
ghq get -p spice-life/spice-life-puppet
ghq get -p spice-life/spicelife-bot
ghq get -p spice-life/spicelife-web
ghq get -p spice-life/spotlights
ghq get -p spice-life/steers
ghq get -p spice-life/tmix-api
ghq get -p spice-life/tmix-backend
ghq get -p spice-life/tmix-manager
ghq get -p spice-life/tmix-res
ghq get -p spice-life/tmix-schema
ghq get -p spice-life/tmix-web
ghq get -p terakoya/rails.terakoya.io
ghq get -p test-unit/test-unit
ghq get -p test-unit/test-unit-rails
ghq get -p twbs/bootstrap
ghq get -p unasuke/AtCoder
ghq get -p unasuke/blog
ghq get -p unasuke/bookshelf_app
ghq get -p unasuke/bootstrap
ghq get -p unasuke/ceifpar
ghq get -p unasuke/do-not-use-atom
ghq get -p unasuke/dotfiles
ghq get -p unasuke/esarea
ghq get -p unasuke/hexapod-robot
ghq get -p unasuke/homebrew-cask
ghq get -p unasuke/homebrew-fonts
ghq get -p unasuke/homebrew-miku
ghq get -p unasuke/hubot
ghq get -p unasuke/hubot-haruka
ghq get -p unasuke/hubot-kotori
ghq get -p unasuke/hubot-rin
ghq get -p unasuke/idobata-hooks
ghq get -p unasuke/idol-handshake
ghq get -p unasuke/imas_api
ghq get -p unasuke/jekyll-test
ghq get -p unasuke/kosen10slt01-my-wip-projects
ghq get -p unasuke/kosen10slt01-self-introduction
ghq get -p unasuke/margarine
ghq get -p unasuke/my-homebrew-setup
ghq get -p unasuke/nerdtree-git-plugin
ghq get -p unasuke/railbook
ghq get -p unasuke/rails.terakoya.io
ghq get -p unasuke/rails_demo_app
ghq get -p unasuke/rails_sample_app
ghq get -p unasuke/reveal.js
ghq get -p unasuke/ruboty-shibuyarin
ghq get -p unasuke/spina-test
ghq get -p unasuke/ss
ghq get -p unasuke/vim
ghq get -p winebarrel/ridgepole
ghq get -p yagi2/hubot-haruka
ghq get -p yascentur/Ricty
ghq get -p yuki24/rambulance
ghq get -p git@git.yagi2.com:unasuke/itamae-recipes.git
